spring.application.name=MigrosBackend

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = false
spring.jpa.hibernate.naming.implicit-strategy = org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${POSTGRES_DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=carbonfiberdev@gmail.com
spring.mail.password=heig fiqc gtqw bhan
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.file.name=./logs/authentication-failures.log

stripe.api.key=sk_test_51R5GK1RpCkckemuqtK5XI8QJxHsbBSGrRrnbDflhRsGruY72jTXPwn4loYYIIFiXN090DwSm174SEi3OMVCzZp0J00NtCoHtU0
# Auth cookie settings
auth.cookie.secure=${AUTH_COOKIE_SECURE:false}
auth.cookie.same-site=${AUTH_COOKIE_SAMESITE:Lax}
